---
- name: Create data fact
  set_fact:
    report_date: "{{ '%Y-%m-%d' | strftime }}"
  delegate_to: "{{ report_host | default('127.0.0.1') }}"
  run_once: true

- name: Create random number
  set_fact:
    random_num: "{{ lookup('password', '/dev/null chars=hexdigits length=6') }}"
    cacheable: no
  delegate_to: localhost
  run_once: true

- name: Create recipient mail address
  set_fact:
    mail_rcpt_to: report_cont_mail
    cacheable: no
  delegate_to: "{{ report_host | default('127.0.0.1') }}"
  run_once: true
  when: mail_rcpt_to is undefined and bind_cont_mail is defined

- name: Create sender mail address
  set_fact:
    mail_from: "no-reply@{{ ansible_domain }}"
    cacheable: no
  delegate_to: "{{ report_host | default('127.0.0.1') }}"
  run_once: true
  when: mail_from is undefined

- name: Create temp path for report
  set_fact:
    report_html: "/var/tmp/Report_OS_{{ report_date }}_{{ random_num }}.html"
    cacheable: no
  delegate_to: "{{ report_host | default('127.0.0.1') }}"
  run_once: true

- name: Create temp path for report
  set_fact:
    report_csv: "/var/tmp/Report_OS_{{ report_date }}_{{ random_num }}.csv"
    cacheable: no
  delegate_to: "{{ report_host | default('127.0.0.1') }}"
  run_once: true

- name: Check service facts
  service_facts: 

- name: Create reports
  template:
    src: report_html.j2
    dest: "{{ report_html }}"
  delegate_to: "{{ report_host | default('127.0.0.1') }}"
  run_once: true
  become: false

- name: Create reports
  template:
    src: report_csv.j2
    dest: "{{ report_csv }}"
  delegate_to: "{{ report_host | default('127.0.0.1') }}"
  run_once: true
  become: false

- name: Send mail report
  mail:
    host: "{{ mail_host | default(omit) }}"
    port: "{{ mail_port | default('25') }}"
    from: "{{ mail_from | default(omit) }}"
    to: "{{ mail_rcpt_to | default(omit) }}"
    subtype: html
    charset: utf8
    subject: Verification role report {{ report_date }}
    attach: 
      - "{{ report_html }}"
      - "{{ report_csv }}"
    body: >
          <h4 style="text-align: center">Please Open the attached HTML report in a modern javascript enabled web browser.</h4>
  delegate_to: "{{ report_host | default('127.0.0.1') }}"
  run_once: true
  become: false
  when: mail_host is defined and mail_from is defined and mail_rcpt_to is defined

- name: Cleanup
  file:
    path: "{{ item }}"
    state: absent
  delegate_to: "{{ report_host | default('127.0.0.1') }}"
  run_once: true
  become: false
  loop:
    - "{{ report_html }}"
    - "{{ report_csv }}"
...
